Initial commit
hrachyam/ERC721 pull request #1
Opened 2022-04-22 05:29 UTC by hrachyam

Initial commit for ERC721 token.

2022-04-24 19:09 UTC, edvardg requested changes

2022-04-24 19:09 UTC, edvardg commented on contracts/MyToken_721.sol
> +        baseURI = string(abi.encodePacked("ipfs://", CIDofMetafiles, "/"));
You can pass URI as a constructor parameter instead of CID to decrease `baseURI` calculation gas.

2022-04-24 19:09 UTC, edvardg commented on contracts/MyToken_721.sol
> +    modifier reentrancyGuard() {
just a minor point - that's good that you have this custom modifier, but we usually use `reentrancyGuard` provided by openzeppelin.

2022-04-24 19:09 UTC, edvardg commented on contracts/MyToken_721.sol
> +    function safeMint(address to) public payable reentrancyGuard {
seems like `to` and `msg.sender` are the same ? Let's remove `to` and use `msg.sender` instead.

2022-04-24 19:09 UTC, edvardg commented on contracts/MyToken_721.sol
> +            require(msg.value == TOKEN_PRICE, "Token price is 0.01 ether!");
minor point - no need to hardcode token price in the error message. You can have different value passed to the contract.

2022-04-24 19:09 UTC, edvardg commented on contracts/MyToken_721.sol
> +        baseURI = string(abi.encodePacked("ipfs://", CIDofMetafiles, "/"));
the same here - lets get rid of string construction and expect new URI as a function param instead of just CID.

2022-04-24 19:09 UTC, edvardg commented on contracts/MyToken_721.sol
> +    uint constant TOKEN_PRICE = 10 ** 16 wei;
can we have token price as constructor parameter ? Let's add this to .env file and load in deployment script.

2022-04-24 19:09 UTC, edvardg commented on migrations/2_deploy_MyToken_721.js
> +  deployer.deploy(MyToken_721, "QmX32MZcdxB74GzoRe9RQp3kai9G9hpSLKVU8RKjw6aR7q");
let's get this from .env file instead of hardcoded value.

2022-04-24 19:09 UTC, edvardg commented on truffle-config.js
> +const {RPC_URL, PRIVATE_KEY, ETHERSCAN_API_KEY} = process.env;
well done. I guess you have `.env` file where you list variables. Let's have `.env.template` file which can be a template for `.env` file and contract deployers can create `.env` file from  `.env.template` and specify correct values for variables.

2022-04-30 07:26 UTC, hrachyam commented
Hi Edo, 

The corresponding changes are done.

Thanks,
Hrach

2022-04-30 15:30 UTC, edvardg approved these changes
Left few minor comments, overall looks good!

2022-04-30 15:30 UTC, edvardg commented on contracts/MyToken_721.sol
> +    uint private _tokenPrice;
Let's make this public to make the price visible for users.

2022-04-30 15:30 UTC, edvardg commented on contracts/MyToken_721.sol
> +        uint mintCount = _minters[msg.sender];
just a minor comment - no need to have a tmp `mintCount` variable, just use `_minters[msg.sender]` in `if` statement.

2022-04-30 15:30 UTC, edvardg commented on contracts/MyToken_721.sol
> +    function balance() external view returns (uint) {
I think no need to have this function as it is possible to get contract balance by web3 functions.

2022-04-30 15:30 UTC, edvardg commented on contracts/MyToken_721.sol
> +        require(_amount <= address(this).balance);
Let's add an error message here.

2022-04-30 17:28 UTC, merged